### ISSUE TITLE
bot ded?

### ISSUE THREAD

**Issue by xSqne** [Scotchex/CatBot#7]
No it's not. The describtion of the problem is not clear, and didn't provide any evidence on the behalf of the statement. 
Removed by the moderator.
Please don't ask questions like this,
KYS

_Originally posted by @Scotchex in https://github.com/Scotchex/CatBot/issues/6#issuecomment-784124320_

**Comment by xSqne** [comment]
it ded?

**Comment by Scotchex** [comment]
Answered in [issue 6](https://github.com/Scotchex/CatBot/issues/6)
